twig:
    exception_controller: App\SiteBundle\Controller\ExceptionController::showException

    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        defaultLocale: 'ua'
        locales:
          - 'ua'
          - 'ru'
          - 'en'
        productImagesPath: '%app.path.product_images%'
        meta: {title: '', description: '', keywords: ''}

    form_themes:
        - 'easy_admin/form/fields.html.twig'
