
easy_admin:
    entities:
        Attribute:
            class: App\Entity\Attribute
            label: 'Attribute'
            list:
                fields:
                    - id
                    - code
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-8', label: 'Basic information', icon: 'pencil' }
                    - { property: 'code' }
                    - { property: 'lang', type: 'collection', type_options: {entry_type: 'App\CMSBundle\Form\AttributeLangEmbeddedForm'}}