
easy_admin:
    entities:
        Attribute:
            class: App\Entity\Attribute
            list:
                title: 'Аттрибуты продуктов'
                fields:
                    - id
                    - { property: 'code', label: 'Уникальный код'}
            new:
                title: 'Создание аттрибута'
                fields:
                    - { type: 'group', css_class: 'col-sm-8', label: 'Основная часть' }
                    - { property: 'code', label: 'Уникальный код' }
            edit:
                title: 'Редактирование аттрибута'
                fields:
                    - { type: 'group', css_class: 'col-sm-8' }
                    - { property: 'code', label: 'Уникальный код' }

                    - { type: 'group', css_class: 'col-sm-8', label: 'Языки' }
                    - { property: 'lang', label: 'Языковые версии', type: 'collection', type_options: {entry_type: 'App\CMSBundle\Form\AttributeLangEmbeddedForm'}}
