
easy_admin:
    entities:
        Content:
            class: App\Entity\Content
            label: 'Content'
            list:
                fields:
                    - id
                    - structure
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-8', label: 'Basic information', icon: 'pencil' }
                    - structure
                    - isActive
                    - { property: 'lang', type: 'collection', type_options: {entry_type: 'App\CMSBundle\Form\ContentLangEmbeddedForm'}}
                    - { property: 'meta', type: 'collection', type_options: {entry_type: 'App\CMSBundle\Form\ContentMetaEmbeddedForm'}}
#                    - { property: 'meta', type: 'collection' }