
easy_admin:
    entities:
        StructureType:
            class: App\Entity\StructureType
            label: 'Structure Types'
            list:
                fields:
                    - id
                    - name
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-5', label: 'Basic information', icon: 'pencil' }
                    - name