
easy_admin:
    entities:
        Structure:
            class: App\Entity\Structure
            label: 'Structure'
            templates:
                new: 'easy_admin/new-lang.html.twig'
                edit: 'easy_admin/edit-lang.html.twig'
            list:
                fields:
                    - id
                    - alias
                    - type
                    - parent
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-5', label: 'Basic information', icon: 'pencil' }
#                    - { type: 'choice' }
                    - { property: 'alias', type: 'text' }
                    - parent
                    - type
                    - { property: 'lang', type: 'collection', label: 'Different Language Items', type_options: { entry_type: 'App\CMSBundle\Form\StructureLangEmbeddedForm', by_reference: false}}
