# This file sets the configuration of the main menu. If your backend is simple,
# you probably can leave the 'menu' option empty and rely on the default menu
# created by EasyAdmin.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    design:
        menu:
            - label: 'Система управления'
              children:
                  - { entity: 'User', icon: 'th-list', label: 'Пользователи' }
                  - { entity: 'Role', icon: 'th-list', label: 'Роли' }
            - label: 'Настройки системы'
              children:
                  - {entity: 'Language', label: 'Языки сайта'}
                  - {entity: 'Variable', label: 'Переменные сайта'}
                  - {entity: 'StructureType', label: 'Типы элементов структур'}
            - label: 'Управление контентом'
              children:
                  - {entity: 'Structure', label: 'Структура'}
                  - {entity: 'Content', label: 'Контент элементов структур'}
                  - {entity: 'Product', label: 'Продукты'}
                  - {entity: 'Attribute', label: 'Атрибуты продуктов'}
            - label: 'Обратная связь'
              children:
                  - {entity: 'Order', label: 'Заказ монтажа'}
                  - {entity: 'Feedback', label: 'Форма с контактов'}